{% set name = "cni-plugins" %}
{% set version = "0.8.1" %}
{% set cni_version = "0.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/containernetworking/plugins/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: 37ba035ae38132e7c6c89935e72b824e9e2136bf92776931b20284003d5c554f  # [not win]

build:
  skip: True  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - {{ compiler('c') }}  # [not win]
  host:
    - cni {{ cni_version }}
  run:
    - cni {{ cni_version }}

test:
  commands:
    - test -f $CNI_PATH/bridge

about:
  home: https://github.com/containernetworking/plugins
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Standard CNI network plugins, maintained by the containernetworking team.
  dev_url: https://github.com/containernetworking/plugins

extra:
  recipe-maintainers:
    - sodre
