{% set version = "1.0.1" %}
{% set cni_version = "0.8.0" %}


package:
  name: cni-plugins
  version: {{ version }}

source:
  url: https://github.com/containernetworking/plugins/archive/v{{ version }}.tar.gz
  sha256: 2ba3cd9f341a7190885b60d363f6f23c6d20d975a7a0ab579dd516f8c6117619

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('go') }}
    - go-licenses
  host:
    - cni {{ cni_version }}
  run:
    - cni {{ cni_version }}

test:
  commands:
    - test -f "${PREFIX}/lib/cni/bandwidth"
    - test -f "${PREFIX}/lib/cni/bridge"
    - test -f "${PREFIX}/lib/cni/dhcp"
    - test -f "${PREFIX}/lib/cni/firewall"
    - test -f "${PREFIX}/lib/cni/flannel"
    - test -f "${PREFIX}/lib/cni/host-device"
    - test -f "${PREFIX}/lib/cni/host-local"
    - test -f "${PREFIX}/lib/cni/ipvlan"
    - test -f "${PREFIX}/lib/cni/loopback"
    - test -f "${PREFIX}/lib/cni/macvlan"
    - test -f "${PREFIX}/lib/cni/portmap"
    - test -f "${PREFIX}/lib/cni/ptp"
    - test -f "${PREFIX}/lib/cni/sbr"
    - test -f "${PREFIX}/lib/cni/static"
    - test -f "${PREFIX}/lib/cni/tuning"
    - test -f "${PREFIX}/lib/cni/vlan"

about:
  home: https://github.com/containernetworking/plugins
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - thirdparty-licenses.txt
  summary: Standard CNI network plugins, maintained by the containernetworking team.
  dev_url: https://github.com/containernetworking/plugins

extra:
  recipe-maintainers:
    - chrisburr
    - mbargull
    - sodre
