{% set name = "cni-plugins" %}
{% set version = "0.8.7" %}
{% set cni_version = "0.8.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/containernetworking/plugins/archive/v{{ version }}.tar.gz  # [not win]
  fn: {{ name }}-{{ version }}.tar.gz  # [not win]
  sha256: de9fa170b4b6d38f6ff5287b313ddaf3c31f70bccb10e971ad59adadae22dd74  # [not win]

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('go') }}  # [not win]
    - {{ compiler('c') }}  # [not win]
  host:
    - cni {{ cni_version }}
    - go
  run:
    - cni {{ cni_version }}

test:
  commands:
    - test -f "${CONDA_PREFIX}/lib/cni/bridge"

about:
  home: https://github.com/containernetworking/plugins
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Standard CNI network plugins, maintained by the containernetworking team.
  dev_url: https://github.com/containernetworking/plugins

extra:
  recipe-maintainers:
    - chrisburr
    - sodre
