travis:
  secure:
    BINSTAR_TOKEN: nUybRnuNJzVrGRLYwZZEW4ABJ6j/pouoPYl7/VQUEo5RHJuj+gDGBdp99GaXcec8DfIh04qGGNJIY6bRVaQWQsaWS1atRIfjtBZqoOHqTod2pRfPGN4g9ex9Ouda11Y6aqI+qNgMoUX3cK/v9hwXaA0Y/unq8S5+syersRm8qQqAYar+Rh4rbOEoGj3I89EMmIGCLksKipWjpRDmDbdJQB4i5jfHKD72ySZc1hJos4Subo1GiIyMYZZjvRUUaJekIiz5tpjULkCTDpqjHai9lBOMiwH/jWIhEUKGvuGgUS6jhtRtmNowmZXahbqxx2fw0wCEGOMr6tJndtuklGH/JeZ3xamzvIHyyBrkfSwisOZOczLyw6wv1VislL60j6uQ9rn2+vYQ1IA+BSG1/j8lVU5J4RLMfgd+1j/0637vpm1NBXlY9GbU/p97eaxDHKGO5lq8FSHPyQSLslUf80b+dCjgS6NaFWmedD0guSrDKWAlefWj34SDzwRllIzHqf2r6TuxfL6Zrn74u+AJNnB7EFXSjllk9NMMuQeKOQ/iW/izuoa52Mk1NmOrN3tOGu7TUZ3LifAno1e4t4V7t2Sa+PfaxQwlKnVnJOT5QY97Wu3CeaVIOlqmZ8ot21wGHswOUTA57czLIq3OPivYuXpQHM7UHTiL3VCmdXaIR8Rq01Q=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
